import argparse
import collections
import datetime as dt
import json
from pathlib import Path


TOOL_LABELS = {
    "codex": "Codex",
    "claude-code": "Claude Code",
    "opencode": "opencode",
    "kimi-code": "Kimi Code",
}


NOISE_PREFIXES = (
    "Continue from where you left off",
    "This session is being continued",
    "claude --resume",
    "codex resume",
    "<turn_aborted>",
)


def parse_args():
    parser = argparse.ArgumentParser(description="Generate a Markdown worklog from ai-log-index.json.")
    parser.add_argument("--index", required=True, help="Index JSON generated by extract_ai_logs.py.")
    parser.add_argument("--out", required=True, help="Output Markdown path.")
    parser.add_argument("--include-empty", action="store_true", help="Include dates with no sessions.")
    return parser.parse_args()


def format_date_nice(iso_date):
    """'2026-05-26' → '2026.5.26'"""
    parts = iso_date.split("-")
    return f"{int(parts[0])}.{int(parts[1])}.{int(parts[2])}"


def clean_text(text):
    text = " ".join(str(text).split())
    return text


def is_noise(text):
    return any(text.startswith(prefix) for prefix in NOISE_PREFIXES)


def user_prompts(record):
    prompts = []
    for message in record.get("messages", []):
        if message.get("role") != "user":
            continue
        text = clean_text(message.get("text", ""))
        if not text or is_noise(text):
            continue
        prompts.append(text)
    return prompts


def assistant_replies(record):
    replies = []
    for message in record.get("messages", []):
        if message.get("role") != "assistant":
            continue
        text = clean_text(message.get("text", ""))
        if not text or is_noise(text):
            continue
        replies.append(text)
    return replies


def summarize_replies(replies, limit=2):
    """Extract key action items or summaries from assistant replies."""
    summaries = []
    seen = set()
    for reply in replies:
        text = reply
        if len(text) > 350:
            text = text[:350] + "..."
        if text in seen:
            continue
        seen.add(text)
        summaries.append(text)
        if len(summaries) >= limit:
            break
    return summaries


def bulletize(prompts, limit=12):
    bullets = []
    seen = set()
    for prompt in prompts:
        text = prompt
        if len(text) > 350:
            text = text[:350] + "..."
        if text in seen:
            continue
        seen.add(text)
        bullets.append(text)
        if len(bullets) >= limit:
            break
    return bullets


def date_range(start_text, end_text):
    start = dt.date.fromisoformat(start_text)
    end = dt.date.fromisoformat(end_text)
    current = start
    while current <= end:
        yield current.isoformat()
        current += dt.timedelta(days=1)


def main():
    args = parse_args()
    data = json.loads(Path(args.index).read_text(encoding="utf-8"))
    records = data.get("records", [])
    by_date = collections.defaultdict(list)
    for record in records:
        by_date[record.get("date")].append(record)

    counts = collections.Counter(record.get("tool") for record in records)
    lines = []
    start = data.get("range", {}).get("start", "")
    end = data.get("range", {}).get("end", "")
    timezone = data.get("range", {}).get("timezone", "Asia/Shanghai")
    lines.append(f"# {format_date_nice(start)} 至 {format_date_nice(end)} AI 协作工作日志")
    lines.append("")
    lines.append(f"生成时间：{dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"分组时区：{timezone}")
    lines.append("")
    lines.append("## 记录概览")
    lines.append("")
    for tool in ("codex", "claude-code", "opencode", "kimi-code"):
        lines.append(f"- {TOOL_LABELS[tool]}：{counts.get(tool, 0)} 个会话")
    missing = [key for key, exists in data.get("source_exists", {}).items() if not exists]
    if missing:
        lines.append(f"- 未找到来源：{', '.join(missing)}")
    lines.append("")

    dates = list(date_range(start, end)) if args.include_empty else sorted(by_date)
    for day in dates:
        records_for_day = by_date.get(day, [])
        if not records_for_day and not args.include_empty:
            continue
        lines.append(f"## {format_date_nice(day)}")
        lines.append("")
        if not records_for_day:
            lines.append("- 未检测到会话记录。")
            lines.append("")
            continue

        # Daily summary across all tools
        day_prompts = []
        for record in records_for_day:
            day_prompts.extend(user_prompts(record))

        if day_prompts:
            lines.append("**当日主题：**")
            themes = bulletize(day_prompts, limit=5)
            for theme in themes:
                lines.append(f"- {theme}")
            lines.append("")

        for tool in ("codex", "claude-code", "opencode", "kimi-code"):
            tool_records = [r for r in records_for_day if r.get("tool") == tool]
            if not tool_records:
                continue
            lines.append(f"### {TOOL_LABELS[tool]}")
            lines.append("")
            for record in tool_records:
                prompts = bulletize(user_prompts(record), limit=12)
                replies = assistant_replies(record)
                reply_summaries = summarize_replies(replies, limit=2)
                cwd = record.get("cwd") or ""
                session_id = record.get("session_id", "")[:8]
                msg_count = record.get("message_count", 0)

                if cwd:
                    lines.append(f"- 工作目录：`{cwd}`")
                lines.append(f"- 会话 `{session_id}` — {msg_count} 条消息")

                if prompts:
                    lines.append("")
                    lines.append("  **用户请求：**")
                    for prompt in prompts:
                        lines.append(f"  - {prompt}")
                else:
                    lines.append("  - 有会话记录，但没有提取到清晰的人工请求；可能主要是工具结果或续接上下文。")

                if reply_summaries:
                    lines.append("")
                    lines.append("  **AI 回应摘要：**")
                    for summary in reply_summaries:
                        lines.append(f"  - {summary}")

                if record.get("commands"):
                    cmd_summary = ", ".join(record["commands"][:5])
                    lines.append("")
                    lines.append(f"  **执行操作：** {cmd_summary}")

                lines.append("")
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
